/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * FitControl
 * API para Gerenciamento de Academia
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type CreateUserBodyPlano =
  (typeof CreateUserBodyPlano)[keyof typeof CreateUserBodyPlano];

export const CreateUserBodyPlano = {
  Mensal: "Mensal",
  Trimestral: "Trimestral",
  Semestral: "Semestral",
  Anual: "Anual",
} as const;

export type CreateUserBodyRole =
  (typeof CreateUserBodyRole)[keyof typeof CreateUserBodyRole];

export const CreateUserBodyRole = {
  Dono: "Dono",
  Aluno: "Aluno",
} as const;

export type CreateUserBodyStatus =
  (typeof CreateUserBodyStatus)[keyof typeof CreateUserBodyStatus];

export const CreateUserBodyStatus = {
  Ativo: "Ativo",
  Inativo: "Inativo",
} as const;

export type CreateUserBody = {
  name: string;
  email: string;
  password: string;
  plano: CreateUserBodyPlano;
  role: CreateUserBodyRole;
  Status: CreateUserBodyStatus;
};

export type CreateUser201 = {
  id: string;
  email: string;
};

export type CreateUser401 = {
  error: string;
  code: string;
};

export type CreateUser404 = {
  error: string;
  code: string;
};

export type CreateUser500 = {
  error: string;
  code: string;
};

export type GetUsers201UsersItemStatus =
  (typeof GetUsers201UsersItemStatus)[keyof typeof GetUsers201UsersItemStatus];

export const GetUsers201UsersItemStatus = {
  Ativo: "Ativo",
  Inativo: "Inativo",
} as const;

export type GetUsers201UsersItemPlano =
  (typeof GetUsers201UsersItemPlano)[keyof typeof GetUsers201UsersItemPlano];

export const GetUsers201UsersItemPlano = {
  Mensal: "Mensal",
  Trimestral: "Trimestral",
  Semestral: "Semestral",
  Anual: "Anual",
} as const;

export type GetUsers201UsersItem = {
  name: string;
  Status: GetUsers201UsersItemStatus;
  plano: GetUsers201UsersItemPlano;
  /** @nullable */
  telefone?: string | null;
  /** @nullable */
  ultimaAvaliacao?: string | null;
};

export type GetUsers201 = {
  totalUsers: number;
  users: GetUsers201UsersItem[];
};

export type GetUsers401 = {
  error: string;
  code: string;
};

export type GetUsers404 = {
  error: string;
  code: string;
};

export type GetUsers500 = {
  error: string;
  code: string;
};

export type UpdateUserBodyPlano =
  (typeof UpdateUserBodyPlano)[keyof typeof UpdateUserBodyPlano];

export const UpdateUserBodyPlano = {
  Mensal: "Mensal",
  Trimestral: "Trimestral",
  Semestral: "Semestral",
  Anual: "Anual",
} as const;

export type UpdateUserBodyRole =
  (typeof UpdateUserBodyRole)[keyof typeof UpdateUserBodyRole];

export const UpdateUserBodyRole = {
  Dono: "Dono",
  Aluno: "Aluno",
} as const;

export type UpdateUserBodyStatus =
  (typeof UpdateUserBodyStatus)[keyof typeof UpdateUserBodyStatus];

export const UpdateUserBodyStatus = {
  Ativo: "Ativo",
  Inativo: "Inativo",
} as const;

export type UpdateUserBody = {
  name?: string;
  plano?: UpdateUserBodyPlano;
  role?: UpdateUserBodyRole;
  Status?: UpdateUserBodyStatus;
};

export type UpdateUser201Plano =
  (typeof UpdateUser201Plano)[keyof typeof UpdateUser201Plano];

export const UpdateUser201Plano = {
  Mensal: "Mensal",
  Trimestral: "Trimestral",
  Semestral: "Semestral",
  Anual: "Anual",
} as const;

export type UpdateUser201Role =
  (typeof UpdateUser201Role)[keyof typeof UpdateUser201Role];

export const UpdateUser201Role = {
  Dono: "Dono",
  Aluno: "Aluno",
} as const;

export type UpdateUser201Status =
  (typeof UpdateUser201Status)[keyof typeof UpdateUser201Status];

export const UpdateUser201Status = {
  Ativo: "Ativo",
  Inativo: "Inativo",
} as const;

export type UpdateUser201 = {
  name: string;
  plano: UpdateUser201Plano;
  role: UpdateUser201Role;
  Status: UpdateUser201Status;
};

export type UpdateUser401 = {
  error: string;
  code: string;
};

export type UpdateUser404 = {
  error: string;
  code: string;
};

export type UpdateUser500 = {
  error: string;
  code: string;
};

export type GetUser200UserPlano =
  (typeof GetUser200UserPlano)[keyof typeof GetUser200UserPlano];

export const GetUser200UserPlano = {
  Mensal: "Mensal",
  Trimestral: "Trimestral",
  Semestral: "Semestral",
  Anual: "Anual",
} as const;

export type GetUser200UserStatus =
  (typeof GetUser200UserStatus)[keyof typeof GetUser200UserStatus];

export const GetUser200UserStatus = {
  Ativo: "Ativo",
  Inativo: "Inativo",
} as const;

export type GetUser200User = {
  name: string;
  plano: GetUser200UserPlano;
  status: GetUser200UserStatus;
};

export type GetUser200MedidasTodasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  userId: string;
  idade: number;
  peso: number;
  alturaCentimetros: number;
  /** @nullable */
  ombro: number | null;
  /** @nullable */
  torax: number | null;
  /** @nullable */
  cintura: number | null;
  /** @nullable */
  abdomen: number | null;
  /** @nullable */
  quadril: number | null;
  /** @nullable */
  braco_relax_direi: number | null;
  /** @nullable */
  braco_contrai_direi: number | null;
  /** @nullable */
  braco_relax_esq: number | null;
  /** @nullable */
  braco_contrai_esq: number | null;
  /** @nullable */
  antebraco_dir: number | null;
  /** @nullable */
  antebraco_esq: number | null;
  /** @nullable */
  coxa_dir: number | null;
  /** @nullable */
  coxa_esq: number | null;
  /** @nullable */
  dobra_triceps: number | null;
  /** @nullable */
  dobra_supraescapular: number | null;
  /** @nullable */
  dobra_suprailica: number | null;
  /** @nullable */
  dobra_adbdominal: number | null;
  /** @nullable */
  dobra_coxa: number | null;
  /** @nullable */
  dobra_peitoral: number | null;
  /** @nullable */
  imc: number | null;
  /** @nullable */
  percentual_gordura: number | null;
  /** @nullable */
  massa_magra: number | null;
  /** @nullable */
  massa_gorda: number | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * @nullable
 */
export type GetUser200MedidasComparacao = {
  [key: string]: {
    atual: number;
    anterior: number;
    diferenca: number;
  };
} | null;

export type GetUser200Medidas = {
  todas: GetUser200MedidasTodasItem[];
  /** @nullable */
  comparacao: GetUser200MedidasComparacao;
};

export type GetUser200 = {
  user: GetUser200User;
  medidas: GetUser200Medidas;
};

export type GetUser401 = {
  error: string;
  code: string;
};

export type GetUser404 = {
  error: string;
  code: string;
};

export type GetUser500 = {
  error: string;
  code: string;
};

export type CreateMedidasBody = {
  idade: number;
  peso: number;
  alturaCentimetros: number;
  ombro?: number;
  torax?: number;
  cintura?: number;
  abdomen?: number;
  quadril?: number;
  braco_relax_direi?: number;
  braco_contrai_direi?: number;
  braco_relax_esq?: number;
  braco_contrai_esq?: number;
  antebraco_dir?: number;
  antebraco_esq?: number;
  coxa_dir?: number;
  coxa_esq?: number;
  dobra_triceps?: number;
  dobra_supraescapular?: number;
  dobra_suprailica?: number;
  dobra_adbdominal?: number;
  dobra_coxa?: number;
  dobra_peitoral?: number;
  percentual_gordura?: number;
};

export type CreateMedidas201 = {
  userId: string;
  idade: number;
  peso: number;
  alturaCentimetros: number;
};

export type CreateMedidas401 = {
  error: string;
  code: string;
};

export type CreateMedidas404 = {
  error: string;
  code: string;
};

export type CreateMedidas500 = {
  error: string;
  code: string;
};

export type UpdateMedidasBody = {
  idade?: number;
  peso?: number;
  alturaCentimetros?: number;
  ombro?: number;
  torax?: number;
  cintura?: number;
  abdomen?: number;
  quadril?: number;
  braco_relax_direi?: number;
  braco_contrai_direi?: number;
  braco_relax_esq?: number;
  braco_contrai_esq?: number;
  antebraco_dir?: number;
  antebraco_esq?: number;
  coxa_dir?: number;
  coxa_esq?: number;
  dobra_triceps?: number;
  dobra_supraescapular?: number;
  dobra_suprailica?: number;
  dobra_adbdominal?: number;
  dobra_coxa?: number;
  dobra_peitoral?: number;
  imc?: number;
  percentual_gordura?: number;
  massa_magra?: number;
  massa_gorda?: number;
};

export type UpdateMedidas201 = {
  userId: string;
  medidaId: string;
};

export type UpdateMedidas401 = {
  error: string;
  code: string;
};

export type UpdateMedidas404 = {
  error: string;
  code: string;
};

export type UpdateMedidas500 = {
  error: string;
  code: string;
};

/**
 * @summary Create User
 */
export type createUserResponse201 = {
  data: CreateUser201;
  status: 201;
};

export type createUserResponse401 = {
  data: CreateUser401;
  status: 401;
};

export type createUserResponse404 = {
  data: CreateUser404;
  status: 404;
};

export type createUserResponse500 = {
  data: CreateUser500;
  status: 500;
};

export type createUserResponseSuccess = createUserResponse201 & {
  headers: Headers;
};
export type createUserResponseError = (
  | createUserResponse401
  | createUserResponse404
  | createUserResponse500
) & {
  headers: Headers;
};

export type createUserResponse =
  | createUserResponseSuccess
  | createUserResponseError;

export const getCreateUserUrl = () => {
  return `/user/`;
};

export const createUser = async (
  createUserBody: CreateUserBody,
  options?: RequestInit,
): Promise<createUserResponse> => {
  return customFetch<createUserResponse>(getCreateUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserBody),
  });
};

/**
 * @summary Get Users
 */
export type getUsersResponse201 = {
  data: GetUsers201;
  status: 201;
};

export type getUsersResponse401 = {
  data: GetUsers401;
  status: 401;
};

export type getUsersResponse404 = {
  data: GetUsers404;
  status: 404;
};

export type getUsersResponse500 = {
  data: GetUsers500;
  status: 500;
};

export type getUsersResponseSuccess = getUsersResponse201 & {
  headers: Headers;
};
export type getUsersResponseError = (
  | getUsersResponse401
  | getUsersResponse404
  | getUsersResponse500
) & {
  headers: Headers;
};

export type getUsersResponse = getUsersResponseSuccess | getUsersResponseError;

export const getGetUsersUrl = () => {
  return `/user/`;
};

export const getUsers = async (
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customFetch<getUsersResponse>(getGetUsersUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update User
 */
export type updateUserResponse201 = {
  data: UpdateUser201;
  status: 201;
};

export type updateUserResponse401 = {
  data: UpdateUser401;
  status: 401;
};

export type updateUserResponse404 = {
  data: UpdateUser404;
  status: 404;
};

export type updateUserResponse500 = {
  data: UpdateUser500;
  status: 500;
};

export type updateUserResponseSuccess = updateUserResponse201 & {
  headers: Headers;
};
export type updateUserResponseError = (
  | updateUserResponse401
  | updateUserResponse404
  | updateUserResponse500
) & {
  headers: Headers;
};

export type updateUserResponse =
  | updateUserResponseSuccess
  | updateUserResponseError;

export const getUpdateUserUrl = (userId: string) => {
  return `/user/${userId}`;
};

export const updateUser = async (
  userId: string,
  updateUserBody: UpdateUserBody,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return customFetch<updateUserResponse>(getUpdateUserUrl(userId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserBody),
  });
};

/**
 * @summary Get User by ID
 */
export type getUserResponse200 = {
  data: GetUser200;
  status: 200;
};

export type getUserResponse401 = {
  data: GetUser401;
  status: 401;
};

export type getUserResponse404 = {
  data: GetUser404;
  status: 404;
};

export type getUserResponse500 = {
  data: GetUser500;
  status: 500;
};

export type getUserResponseSuccess = getUserResponse200 & {
  headers: Headers;
};
export type getUserResponseError = (
  | getUserResponse401
  | getUserResponse404
  | getUserResponse500
) & {
  headers: Headers;
};

export type getUserResponse = getUserResponseSuccess | getUserResponseError;

export const getGetUserUrl = (userId: string) => {
  return `/user/${userId}`;
};

export const getUser = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserResponse> => {
  return customFetch<getUserResponse>(getGetUserUrl(userId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create medidas User
 */
export type createMedidasResponse201 = {
  data: CreateMedidas201;
  status: 201;
};

export type createMedidasResponse401 = {
  data: CreateMedidas401;
  status: 401;
};

export type createMedidasResponse404 = {
  data: CreateMedidas404;
  status: 404;
};

export type createMedidasResponse500 = {
  data: CreateMedidas500;
  status: 500;
};

export type createMedidasResponseSuccess = createMedidasResponse201 & {
  headers: Headers;
};
export type createMedidasResponseError = (
  | createMedidasResponse401
  | createMedidasResponse404
  | createMedidasResponse500
) & {
  headers: Headers;
};

export type createMedidasResponse =
  | createMedidasResponseSuccess
  | createMedidasResponseError;

export const getCreateMedidasUrl = (userId: string) => {
  return `/medidas/${userId}`;
};

export const createMedidas = async (
  userId: string,
  createMedidasBody: CreateMedidasBody,
  options?: RequestInit,
): Promise<createMedidasResponse> => {
  return customFetch<createMedidasResponse>(getCreateMedidasUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMedidasBody),
  });
};

/**
 * @summary Update medidas User
 */
export type updateMedidasResponse201 = {
  data: UpdateMedidas201;
  status: 201;
};

export type updateMedidasResponse401 = {
  data: UpdateMedidas401;
  status: 401;
};

export type updateMedidasResponse404 = {
  data: UpdateMedidas404;
  status: 404;
};

export type updateMedidasResponse500 = {
  data: UpdateMedidas500;
  status: 500;
};

export type updateMedidasResponseSuccess = updateMedidasResponse201 & {
  headers: Headers;
};
export type updateMedidasResponseError = (
  | updateMedidasResponse401
  | updateMedidasResponse404
  | updateMedidasResponse500
) & {
  headers: Headers;
};

export type updateMedidasResponse =
  | updateMedidasResponseSuccess
  | updateMedidasResponseError;

export const getUpdateMedidasUrl = (userId: string, medidaId: string) => {
  return `/medidas/user/${userId}/${medidaId}`;
};

export const updateMedidas = async (
  userId: string,
  medidaId: string,
  updateMedidasBody: UpdateMedidasBody,
  options?: RequestInit,
): Promise<updateMedidasResponse> => {
  return customFetch<updateMedidasResponse>(
    getUpdateMedidasUrl(userId, medidaId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateMedidasBody),
    },
  );
};
